project:
  type: website
  output-dir: docs

website:
  title: "Deepshika Saravanan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - CV.qmd
       

format:
  html:
    theme: minty
    css: |
      
    body {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        background-color: #f9f9f9;
        color: #333333;
        margin: 0;
        padding: 0;
      }

      .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
      }

      h1, h2, h3 {
        color: #0066cc;
      }

      p {
        line-height: 1.5;
      }

      .intro {
        background-color: #0066cc;
        color: #ffffff;
        padding: 20px;
        margin-bottom: 20px;
      }

      .intro h1 {
        font-size: 2em;
        margin-bottom: 10px;
      }

      .intro p {
        font-size: 1.2em;
      }

      .section {
        margin-bottom: 30px;
      }

      .section h2 {
        font-size: 1.5em;
        margin-bottom: 10px;
      }

      .section p {
        font-size: 1.2em;
      }

      .footer {
        background-color: #333333;
        color: #ffffff;
        text-align: center;
        padding: 10px 0;
        position: absolute;
        bottom: 0;
        width: 100%;
      }
   

editor: visual

